import assert from "node:assert/strict";
import { McpBridge } from "../dist/index.js";
import { ReferenceProtocol } from "../../reference-ts/dist/index.js";

const at = "2026-08-09T19:20:00Z";
const sourceUri = "mcp://demo/resource";
const source = { sourceUri, observedAt: at, version: { scheme: "mcp.epoch", token: "1" }, validator: { id: "mcp", operation: "read" } };
const envelope = { specVersion: "premise/0.1", memoryId: "memory:mcp", provenance: [source], validity: { status: "FRESH", checkedAt: at, policy: "VERSIONED" }, dependsOn: [] };
let current = { sourceUri, version: { scheme: "mcp.epoch", token: "1" } };
const reader = { async read(uri) { if (uri !== sourceUri) throw new Error("missing"); return current; } };
const protocol = new ReferenceProtocol();
protocol.register(envelope);
const bridge = new McpBridge(protocol, reader);
bridge.subscribe(sourceUri, [envelope.memoryId]);
current = { sourceUri, version: { scheme: "mcp.epoch", token: "2" } };
bridge.signal({ eventId: "mcp-1", sourceUri, version: current.version, occurredAt: at });
assert.equal(protocol.check([envelope.memoryId]).items[0].decision, "REVALIDATE");
await bridge.reread([envelope.memoryId]);
assert.equal(protocol.check([envelope.memoryId]).items[0].decision, "REJECT");

const unchangedProtocol = new ReferenceProtocol();
const unchangedEnvelope = { ...envelope, memoryId: "memory:mcp-unchanged", provenance: [{ ...source, sourceUri: "mcp://demo/unchanged" }] };
unchangedProtocol.register(unchangedEnvelope);
const unchangedBridge = new McpBridge(unchangedProtocol, { async read() { return { sourceUri: "mcp://demo/unchanged", version: { scheme: "mcp.epoch", token: "1" } }; } });
const firstSubscription = unchangedBridge.subscribe("mcp://demo/unchanged", [unchangedEnvelope.memoryId]);
const secondSubscription = unchangedBridge.subscribe("mcp://demo/unchanged", [unchangedEnvelope.memoryId]);
firstSubscription.unsubscribe();
const unchangedReport = await unchangedBridge.reread([unchangedEnvelope.memoryId]);
assert.equal(unchangedReport.items[0].result, "UNCHANGED");
secondSubscription.unsubscribe();

const mismatchProtocol = new ReferenceProtocol();
const mismatchEnvelope = { ...envelope, memoryId: "memory:mcp-mismatch", provenance: [{ ...source, sourceUri: "mcp://demo/mismatch" }] };
mismatchProtocol.register(mismatchEnvelope);
const mismatchBridge = new McpBridge(mismatchProtocol, { async read() { return { sourceUri: "mcp://demo/other", version: { scheme: "mcp.epoch", token: "1" } }; } });
mismatchBridge.subscribe("mcp://demo/mismatch", [mismatchEnvelope.memoryId]);
const mismatchReport = await mismatchBridge.reread([mismatchEnvelope.memoryId]);
assert.equal(mismatchReport.items[0].result, "UNKNOWN");

const timeoutProtocol = new ReferenceProtocol();
const timeoutEnvelope = { ...envelope, memoryId: "memory:mcp-timeout", provenance: [{ ...source, sourceUri: "mcp://demo/timeout" }] };
timeoutProtocol.register(timeoutEnvelope);
const timeoutBridge = new McpBridge(timeoutProtocol, { async read() { throw new Error("transport timeout"); } });
timeoutBridge.subscribe("mcp://demo/timeout", [timeoutEnvelope.memoryId]);
const timeoutReport = await timeoutBridge.reread([timeoutEnvelope.memoryId]);
assert.equal(timeoutReport.items[0].result, "UNKNOWN");

const sharedProtocol = new ReferenceProtocol();
const sharedSourceUri = "mcp://demo/shared";
const sharedSource = { ...source, sourceUri: sharedSourceUri };
const sharedEnvelopeA = { ...envelope, memoryId: "memory:mcp-shared-a", provenance: [{ ...sharedSource, version: { scheme: "mcp.epoch", token: "1" } }] };
const sharedEnvelopeB = { ...envelope, memoryId: "memory:mcp-shared-b", provenance: [{ ...sharedSource, version: { scheme: "mcp.epoch", token: "0" } }] };
sharedProtocol.register(sharedEnvelopeA);
sharedProtocol.register(sharedEnvelopeB);
let sharedReads = 0;
const sharedBridge = new McpBridge(sharedProtocol, { async read(uri) { sharedReads += 1; return { sourceUri: uri, version: { scheme: "mcp.epoch", token: "2" } }; } });
sharedBridge.subscribe(sharedSourceUri, [sharedEnvelopeA.memoryId, sharedEnvelopeB.memoryId]);
const sharedReport = await sharedBridge.reread([sharedEnvelopeA.memoryId, sharedEnvelopeB.memoryId]);
assert.equal(sharedReads, 1);
assert.deepEqual(sharedReport.items.map((item) => [item.memoryId, item.result]), [[sharedEnvelopeA.memoryId, "CHANGED"], [sharedEnvelopeB.memoryId, "CHANGED"]]);
console.log("mcp-bridge tests passed");
